---
date: "2011/12/31"
title: "2011 in review"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2011/12/2011-in-review.html)*.

In the spirit of Chris Guillebeau's [Annual Review](http://chrisguillebeau.com/3x5/how-to-conduct-your-own-annual-review/), I decided to take a few minutes this morning to review what worked well and what didn't 2011 and look forward to 2012.Goals:Last year I set [three goals for 2011](http://www.russpoldrack.org/2011/01/goals-for-new-year.html).  Here's how they fared.FAIL: Work toward a travel moratorium for 2012.  This started with me responding to all requests with "I'm sorry, but I'm not traveling at all for work in 2012."  At some point that became untenable, and the floodgates opened.  At this point, I am still planning to travel less in 2012 than in 2011, but will still probably take 8-10 trips.SUCCESS: Improve climbing skills well enough to lead climb. My climbing skills have improved enormously over the last year, and in the summer I began lead climbing at the rock gym, where I can now lead a number of routes in the 5.9 range.  I was not able to lead outside, mostly because the weather in December did not cooperate, but I plan to do so very soon.SUCCESS: No new web projects. I only purchased one new domain name this year, and that was for a project that had been hatched in 2010.  We have instead focused heavily on our existing projects, particularly [openfmri.org](http://openfmri.org/). Here are my goals for 2012:Improve my posture.  Some nagging neck and back issues this year have highlighted the need to improve my posture.  Who knows, I might even [get some mental benefits from it as well](http://www.ncbi.nlm.nih.gov/pubmed/10457761).Improve my code management.  In the last year I have started integrating source code management (using git) into my workflow (see [my github repo](https://github.com/poldrack) for a tour of some of my adventures during the last year).  However, it still has not become a habit for me during everyday coding. Exercise on every trip.  One of the reasons that I find travel so disruptive is that it interferes with my fitness routine.  I carry my yoga mat on nearly every trip, and this year I did a fairly good job of exercising while on the road, but I was not very consistent.  Next year I plan to make sure that I get some exercise on every trip, even if it's just some burpees and squats in the hotel room. I hope it's not true that [making these goals public will make them harder to achieve](http://www.ncbi.nlm.nih.gov/pubmed/19389130)!StatsCountries visited: 7Miles flown: 76,162Talks given: 12Papers published: 14Grants funded: 2Property crimes (committed against me, not by me): 2Best meals:1. Tasting menu at [Congress](http://congressaustin.com/congress/)2. Lunch at [Les Arcenuax, Marseille](http://www.les-arcenaulx.com/)3. Tie between [Franklin BBQ](http://franklinbarbecue.com/) and [JMueller BBQ](http://jmuellerbbq.com/)4. Tasting menu at [Uchi](http://www.uchiaustin.com/) (the meal that sealed our transition to full-blown carnivores)

---

## 3 comments captured from [original post](https://russpoldrack.blogspot.com/2011/12/2011-in-review.html) on Blogger

**Janet said on 2011-12-31**

Great post. Do you think a standing desk might help with the posture issues, since (i presume) so much of your day is spent at a keyboard?

**Russ Poldrack said on 2011-12-31**

probably would help - In fact, I have started standing at work whenever I can (e.g. conference calls).

**Ace said on 2011-12-31**

Saddle chairs are a good way to improve posture &amp; ergonomics. pricey but a good investment given time spent on computer: http://www.haginc.com/products/hag-capisco/

