project:
  type: website
  output-dir: docs


website:
  title: "Russ Poldrack's blog"
  google-analytics: "G-R0530E6SNQ"
  navbar:
    right:
      - text: "About"
        href: https://profiles.stanford.edu/russell-poldrack
      - icon: github
        href: https://github.com/poldrack
      - icon: mastodon
        href: https://mastodon.online/@Russpoldrack
format:
  html:
    theme: flatly
    css: styles.css



