---
date: "2016/04/18"
title: "How folksy is psychology?  The linguistic history of cognitive ontologies"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2016/04/how-folksy-is-psychology-linguistic.html)*.

I just returned from a fabulous meeting on[ Rethinking the Taxonomy of Psychology,](http://www.rotman.uwo.ca/events-2/rethinking-the-taxonomy-of-psychology-conference/) hosted by [Mike Anderson](http://www.agcognition.org/mlja.html), [Tim Bayne](http://www.rotman.uwo.ca/members/tim-bayne/), and [Jackie Sullivan](http://www.rotman.uwo.ca/members/jacqueline-sullivan/).  I think that in another life I must have been a philosopher, because I always have so much fun hanging out with them, and this time was no different.  In particular, the discussions at this meeting moved from simply talking about whether there is a problem with our ontology (which is [old](http://www.ncbi.nlm.nih.gov/pubmed/20964882) [hat](https://mitpress.mit.edu/books/after-phrenology) [at](http://www.ncbi.nlm.nih.gov/pubmed/25076977) [this](http://www.ncbi.nlm.nih.gov/pubmed/25164049) [point](http://www.ncbi.nlm.nih.gov/pubmed/26393866)) to specifically how we can think about using neuroscience to revise the ontology.  I was particularly excited to see all of the interest from a group of young philosophers whose work is spanning philosophy and cognitive neuroscience, who I am counting on to keep the field moving forward!I have long made the the point that the conceptual structure of current psychology is not radically different from that of William James in the 19th century.  This seems plausible on its face if you look at some of the section headings from his 1890 “To How Many Things Can We Attend At Once?”“The Varieties Of Attention.”“The Improvement Of Discrimination By Practice”“The Perception Of Time.”“Accuracy Of Our Estimate Of Short Durations”“To What Cerebral Process Is The Sense Of Time Due?”“Forgetting.”“The Neural Process Which Underlies Imagination”“Is Perception Unconscious Inference?”“How The Blind Perceive Space.”“Emotion Follows Upon The Bodily Expression In The Coarser Emotions At Least.”“No Special Brain-Centres For Emotion”“Action After Deliberation”:Beyond the sometimes flowery language, there are all topics that one could imagine being topics of research papers today, but for my talk I wanted to see if there was more direct evidence that the psychological ontology is less different (and thus more "folksy") than ontologies in other sciences.   To address this, I did a set of analyses that looked at the linguistic history of terms in the contemporary psychological ontology (as defined in the [Cognitive Atlas](http://www.cognitiveatlas.org/)) as compared to terms from contemporary biology (as enshrined in the [Gene Ontology](http://geneontology.org/)).  I started (with a bit of help from [Vanessa Sochat](http://vsoch.github.io/)) by examining the proportion of terms from the Cognitive Atlas that were present in James' Principles (from the full text available [here](http://psychclassics.yorku.ca/James/Principles/)).  This showed that 22.9% of the terms in our current ontology were present in James's text (some examples are: goal, deductive reasoning, effort, false memory, object perception, visual attention, task set, anxiety, mental imagery, unconscious perception, internal speech, primary memory, theory of mind, judgment). How does this compare to biology?  To ask this, I obtained two biology textbooks published around the same time as James' Principles (T. H. Huxley's [Course of Elementary Instruction in Practical Biology](https://books.google.com/books?id=Y5xlhbDnzbwC&pg=PR1&lpg=PR1&dq=huxley+elementary+instruction+practical+biology&source=bl&ots=M2z6Sot6tM&sig=0Hj2qFVIJ-fg2oytKygENkRpZcc&hl=en&sa=X&ved=0ahUKEwis0_bCtZjMAhWB6yYKHW2NBaMQ6AEIMTAD#v=onepage&q=huxley%20elementary%20instruction%20practical%20biology&f=false) from 1892, and T. J. Parker's [Lessons in Elementary Biology](https://books.google.com/books?id=6tRLAAAAYAAJ&dq=parker+lessons+in+elementary+biology&source=gbs_navlinks_s) from 1893), which are both available in full text from Google Books.  In each of these books I assessed the presence of each term from the Gene Ontology, separately for each of the GO subdomains (biological processes, molecular functions, and cellular components).  Here are the results:   Huxley Parker Overlap  biological process (28,566) 0.09% (26) 0.1% (32) 20  molecular functions (10,057) 0 0 -  cellular components (3,903) 1.05% (41) 1.01% (40) 25 The percentages of overlap are much lower, perhaps not surprisingly since the number of GO terms is so much larger than the number of Cognitive Atlas terms.  But even the absolute numbers are substantially lower, and there is not one mention of any of the GO molecular functions (striking but completely unsurprising, since molecular biology would not be developed for many more decades).These results were interesting, but it could be that they are specific to these particular books, so I generalized the analysis using the [Google N-Gram corpus](https://books.google.com/ngrams), which indexes the presence of individual words and phrases across more than 3 million books.  Using a [python package](https://github.com/econpy/google-ngrams) that accesses the ngram viewer API, I estimated the presence of all of the Cognitive Atlas terms as well as randomly selected subsets of each of the GO subdomains in the English literature between 1800 and 2000; I'm planning to rerun the analysis on the full corpus using the downloaded version of the N-grams corpus, but using this API required throttling that prevented me from the full sets of GO terms.  Here are the results for the Cognitive Atlas:It is difficult to imagine stronger evidence that the ontology of psychology is relying on pre-scientific concepts; around 80% of the one-word terms in the ontology were already in use in 1800! Compare this to the Gene Ontology terms (note that there were not enough single-word molecular function terms to get a reasonable estimate):It's clear that the while a few of the terms in these ontologies were in use prior to the development of the biosciences, the proportion is much smaller than what one sees for psychology. In my talk, I laid out two possibilities arising from this:Psychology has special access to its ontology that obviates the need for a rejection of folk conceptsPsychology is due for a conceptual revolution that will leave behind at least some of our current conceptsMy guess is that the truth lies somewhere in between these.  The discussions that we had at the meeting in London provided some good ideas about how to conceptualize the kinds of changes that neuroscience might drive us to make to this ontology. Perhaps the biggest question to come out of the meeting was whether a data-driven approach can ever overcome the fact that the data were collected from experiments that are based on the current ontology. I am guessing that it can (given, e.g. [the close relations between brain activity present in task and rest](http://science.sciencemag.org/content/352/6282/216.full.pdf+html)), but this remains one of the biggest questions to be answered.  Fortunately there seems to be lots of interest and I'm looking forward to great progress on these questions in the next few years.

---

## 6 comments captured from [original post](https://russpoldrack.blogspot.com/2016/04/how-folksy-is-psychology-linguistic.html) on Blogger

**Michael Frank said on 2016-04-18**

Nice post! A third possibility relative to your list is that a goal of psychology is to provide a level of explanation that ties the concepts of interest to our folk psychology to a more precise set of constructs. These more precise constructs nevertheless use (&quot;overload&quot;) the same terms. So although William James talked about memory and attention, we taxonomize these in ways that correspond to - but build upon - the folk concept, e.g. using terms like &quot;declarative memory&quot; to add details. <br /><br />Also - when you study something like language learning (like me) - it's weird to think that you'd want to abandon the folk ontology, which includes useful concepts like words, sentences, syllables, etc. Those really *are* the meaningful units of behavior.

**Russ Poldrack said on 2016-04-18**

great points!  we had a good bit of discussion about whether the current terms are used in ways that are distinct from the folk concepts.  I think that you are right that in some cases they are overloaded (e.g. the fractionation of &quot;memory&quot; - though the fundamental subcomponents like recollection and habit were also clear to James).  interesting point regarding language, hadn't thought of that.

**KalinaChristoff said on 2016-04-18**

Great post, Russ. It made me think of what's happening in the scientific study of mind-wandering right now. Mind wandering in some form or another has been of course a folksy concept for a long time. But as psychologists and neuroscientists started to more intensely investigate it in the last 10-15 years, the scientific concept &quot;developed&quot; to become ostensibly &quot;better defined&quot;: it started being defined as &quot;task-unrelated or stimulus-independent thought&quot; (a definition that is overly narrow in my opinion). Through my collaborations with philosophers, I have recently become convinced and have argued that what we actually need in the study of mind-wandering currently is precisely going back to the original &quot;folksy&quot; meaning of this term. That's because the scientific definition has become too narrow, and too content focused, while ignoring the original &quot;folksy&quot; intuition that mind-wandering is about how thoughts move (and not what their content is about). So at least in this case, you could say progress could mean going back to the concept's folksy origin: we argue that the study of mind-wandering is due for a conceptual revolution by returning back to its &quot;folksy&quot; roots and espousing them a bit more fully.

**Russ Poldrack said on 2016-04-19**

Interesting point.  it seems to me that if the scientifically defined concepts are too narrow, then they should be extended to cover the phenomena of interest.  It seems to me that you are saying that the field should retreat back into the phenomena themselves (which are what the folk terms refer to), but that doesn't actually seem like a scientiific move to me

**Brad Buchsbaum said on 2016-04-19**

An interesting case study in language transformation in psychology is occurring in the memory literature: consider the (meteoric?) rise of the two terms &quot;pattern separation&quot; and &quot;pattern completion&quot;. These terms come from computational models of the hippocampus and are being used in a way that in some sense bypasses the inherited folk-language of the psychology of memory.<br /><br />Although the terms lack folk analogues, one sometimes feels as if they are being used as stand-ins for a folk term. When we have a &quot;recollection&quot; are we &quot;pattern completing&quot;? And was that really &quot;pattern separation&quot; or was it &quot;recollect-to-reject&quot;? I have seen the terms sometimes substituted for the old folk term -- is this progress?<br /><br />I do think the move toward &quot;computational terms&quot; over phenomenological ones is probably a welcome trend -- but there is going to a long period where folk terms and &quot;computational terms&quot; blend together a bit and compete for ontological real estate.

**Russ Poldrack said on 2016-04-19**

I think this is a great example!

