---
author: "Russ Poldrack"
date: 2010/12/15
title: on carbon footprints and biased judgments
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2010/12/on-carbon-footprints-and-biased.html)*.

I recently bought a new SUV.  I was in the market for a new car, and really liked the styling of the [Toyota FJ Cruiser](http://www.toyota.com/fjcruiser/), not to mention its utility for carrying all the various stuff that I need to carry.  When I announced my purchase on Facebook, it occasioned a number of humorous jabs from my friends, which I was sure that I deserved; after all, I had just bought a monstrous gas-guzzler (17 MPG in town, 21 on the highway)! These comments also inspired me to think more about how we judge the impact of our choices on the environment. Everyone knows that driving a fuel-efficient, low-emission vehicle is better for the environment than a gas-guzzler, because this issue is prominent in the news as well as car advertisements.  However, a large body of psychological research has shown that our judgments about things like this are often biased.  Rather than basing our judgments on statistics (as we should if we want them to be accurate), we often use rules of thumb, or "heuristics" as they are known in psychology.  For example, when asked to judge how common something is, we often base our judgments on how readily an example of it comes to mind.  This "[availability heuristic](http://en.wikipedia.org/wiki/Availability_heuristic)" is the reason why people's judgments about the prevalence of crime often don't match crime statistics; even when crime is going down, news reports of criminal acts easily come to mind and bias us to think that crime is actually increasing. When it comes to the impacts of our behavior on the environment, the recent popularity of hybrid cars has made the environmental consequences of driving highly available in our mind, and thus we think of driving as a major component of our carbon footprint.  However, some analysis using the various carbon footprint calculators on the web shows that we may be overestimating the relative benefit of buying a fuel-efficient car in comparison to other lifestyle choices that we make. According to the [carbonfootprint.com calculator](http://calculator.carbonfootprint.com/calculator.aspx), my FJ Cruiser will produce about 3.25 tons of CO2 over a year of driving my average of 6000 miles. If I had purchased a Toyota Prius, I would produce 1.17 tons over the same year, a savings a just over 2 tons of CO2. That sounds like a big reduction in CO2 emissions, but how does it compare to some other choices that we might make?  A round trip flight from LAX to JFK produces 2.41 tons of CO2 per passenger when the effects of water vapor are taken into account.  Thus, a single airline flight obliterates the benefits of driving a hybrid for a year.  Another choice that has a big environmental impact is eating meat.  According to the [Nature Conservancy's calculator](http://www.nature.org/initiatives/climatechange/calculator/), eliminating meat from one's diet reduces one's yearly carbon footprint by 3.2 tons; again, more effective than buying a hybrid. The choice that has the largest environmental impact by far is having children.  According to [a study published last year](http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6VFV-4V8FFCG-1&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&_docanchor=&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=411a4bfd17ad84a0d2fd4c0a9061c717), the lifetime carbon footprint of an American child is estimated to be more than 9,000 tons of CO2.  Thus, the environmental impact of having just one child in the United States is equivalent to 1,450 people each driving a Cadillac Escalade 10,000 miles over one year.  Another way to look at it is that the yearly CO2 savings due to all of the hybrid vehicles sold in the US in 2009 ([290,272 according to HybridCars.com](http://www.hybridcars.com/hybrid-sales-dashboard/december-2009-dashboard.html)) is enough to offset the lifetime carbon impact of about 64 American children. How can we improve our ability to make accurate judgments in situations like this?  First we need to be aware of our biases, but this is difficult: Research by [Emily Pronin from Princeton University](http://weblamp.princeton.edu/~psych/psychology/research/pronin/index.php) has shown that humans often have a "blind spot" regarding their own biases. Research subjects in one of her studies (who were randomly chosen passengers at the San Francisco airport) rated themselves as substantially less biased than the "average passenger."  Once we realize that we are all biased, we can start to try to overcome those biases.  One way to overcome biases is to slow down; when we take the time to take in more evidence regarding a judgment or decision, we are more likely to rely upon information that is less biased than the "gut feeling" that our heuristics provide for us.