---
date: "2010/11/21"
title: "My personal computing history"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2010/11/my-personal-computing-history.html)*.

 My generation may be the last to ever have known a world without ubiquitous computing. It’s now almost impossible to imagine a computer being a thing that sits in the corner at the school library and gets used only by a few geeky kids, but in my high school that’s exactly what it was. I’ve recently been trying to reconstruct the history of different computers that I played with and owned back in those days; here is my first pass at a personal computing history, helped in large part by the awesome amount of computer history information that’s available online.My first exposure to computers came during 1981-1983 when I was in high school, though several different paths (the order of which is slightly hazy me at this point). The first system that I remember programming on was the [TI 99/4A](http://en.wikipedia.org/wiki/Texas_Instruments_TI-99/4A), which was a “home computer” released in 1981 (we probably got it around 1982-1983). It came with relatively little software, but I do remember playing a number of games including “TI Invaders” which was their clone of the Space Invaders game. The programs were released on cartridges, more like a video game system than a personal computer. The machine came installed with “TI BASIC” which was a pretty rudimentary version of BASIC. We didn’t have a hard drive, but it was possible to save programs to cassette tape. I don’t remember much about what kind of programming I did on this system, though I’m pretty sure it was all text-based. Northstar AdvantageAround the same time, my father purchased a computer for his accounting office, back when this was just becoming common. It was a [Northstar Advantage](http://www.old-computers.com/museum/computer.asp?c=652), which was resold with a GBC logo. This machine was released in 1982, right after the release of the first IBM PC. It ran an operating system called [CP/M](http://en.wikipedia.org/wiki/CP/M), which was similar to but predated Microsoft’s DOS. The apps that I remember using included [WordStar](http://en.wikipedia.org/wiki/WordStar) (word processing) and [dBASE](http://en.wikipedia.org/wiki/DBase) (a database program). I don’t think I actually programmed on this system, but it was my first experience with command line interfaces ([PIP](http://en.wikipedia.org/wiki/Peripheral_Interchange_Program), anyone?). Apple IIeIn our high school there was an [Apple IIe](http://www.old-computers.com/museum/computer.asp?st=1&c=83) in the library that was almost always free. I was ostensibly on the tennis team when I was a senior in high school, but given that I wasn’t very good at tennis, the coach was happy to let me go to the library and play with the computer instead. This system had a great advantage over the TI at home, which was that I could save programs to 5 ¼” floppy disk. This is the first machine that I remember doing any graphics programming on, though I’m sure that it was incredibly rudimentary. In the summers of 1984 and 1985, I worked at a local bank helping them to automate some of their records. The bank had just recently purchased a new [IBM PC/AT](http://en.wikipedia.org/wiki/IBM_Personal_Computer/AT) which was the second generation of IBM PC’s. It had such amazing features as 16 MB of RAM and a 20 MB hard drive. I primarily used [Lotus 1-2-3 ](http://en.wikipedia.org/wiki/Lotus_1-2-3)(an early spreadsheet program). However, in the moments between real work, I would also take advantage of the machine’s modem to dial into a number of [BBS sites](http://en.wikipedia.org/wiki/Bulletin_board_system). It’s hard for me to remember exactly what I found on these sites or how I even found out about them, but it was basically like a very earlier version of the web that one could call into for free. I think I mostly used them to download software. Macintosh SE/30During most of my college career I did not have my own computer; very few students did. If we needed one, we would go to the computer lab on campus, which is where I was introduced to Macintosh (Plus or SE) computers. In my senior year of college the [Mac SE/30](http://en.wikipedia.org/wiki/Macintosh_SE/30) was released, and my parents were nice enough to plop down several thousand dollars to buy me one before I headed off to graduate school, along with an ImageWriter II dot-matrix printer. This machine was my workhorse throughout graduate school. I addition to writing papers, I was my platform for learning other languages including PASCAL and C. It was the system on which I wrote my first simulations, which would be published [here](http://www.poldracklab.org/Publications/pdfs/Psychonomic%20Bulletin%20and%20Review%201996%20Poldrack.pdf) (though the actual simulations for that paper were run on a Sun UNIX system at the Beckman Institute because it was so much faster than my SE/30).  PowerTower ProWhen I arrived at Stanford for my postdoc in 1995, it was definitely time to upgrade. I was lucky enough to be in the market during the short period in which Mac clones were available, and I bought a [Power Computing Power Tower Pro](http://www.everymac.com/systems/powercc/powertower_pro/powertower_pro180.html), which was one of my favorite computers ever. It was this machine on which I first started playing serious with Linux (using mkLinux IIRC). The PowerTower Pro is the last machine that I’ve owned that I think could be legitimately called “historical”, so that’s where my story ends for now.       

---

## 3 comments captured from [original post](https://russpoldrack.blogspot.com/2010/11/my-personal-computing-history.html) on Blogger

**MexHistorian said on 2010-11-21**

I remember the SE/30--I came over and spent the day at the Nutty Pecan putting my history paper together. (I got an A on it with the comment &quot;Pretty good&quot; from the prof.) Good times.

**Unknown said on 2010-11-21**

In 1993 you asked me if you should buy a computer or go to Europe.  I told you computers were like sex -- you shouldn't have to pay for them.  You came to Europe...

**Russ Poldrack said on 2010-11-30**

That was great advice Gordon!

