---
date: "2020/01/24"
title: "Talking remotely: Lessons learned so far"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2020/01/talking-remotely-lessons-learned-so-far.html)*.

Since making [my commitment to reduce air travel for academic purposes](http://www.russpoldrack.org/2019/06/why-i-will-be-flying-less.html), I’ve been giving a lot more remote talks.  In the last 5 months I have given 10 remote talks - many thanks to those who have agreed to host me virtually rather than in person: September: National Academies Data Science in the Cloud workshop, Washington, DC National Academies Brain Health Across the Lifespan workshop, Washington, DC October: Cognitive Science Colloquium, Institut d'Etudes Cognitives, École Normale Supérieure, Paris, France. Johns Hopkins University Dept. of Electrical and Computer Engineering, Distinguished Lecturer Series, Baltimore, MD NIMH  Talk Series on Machine Learning in Brain Imaging, Neuroscience, and Psychology, Bethesda, MD November: Santa Fe Institute, Cognitive Regime Shift meeting, Santa Fe, NM Montreal Neurological Institute, Open Science Symposium, Montreal Johns Hopkins University Dept. of Biostatistics,  Bethesda, MD January: IBI Data Standards and Sharing Working Group, Tokyo, Japan Max Planck School of Cognition, Berlin, GermanySome of these were already bunched together so they wouldn’t have required separate flights, but even considering that, my back-of-the-envelope calculation shows that these flights would have resulted almost 7 tons of CO2 being generated (as estimated using [https://www.icao.int/environmental-protection/Carbonoffset/Pages/default.aspx](https://www.icao.int/environmental-protection/Carbonoffset/Pages/default.aspx)).  Not to mention lots of physiological stress from jet lag, and travel costs to be borne by my hosts. So in many ways it’s been a huge win for everyone. An important issue, however, is what the experience was like, both for my hosts and the attendees and for myself.  The visits varied from talks with a short Q&A session, to extended visits in which my talk was followed by individual meetings with researchers. For me the experience has been very positive — certainly not as good as being there in some ways, but still very satisfying.  The least satisfying experience for me as a speaker has been in situations where I give a talk without time for Q&A afterwards.  I think that my hosts have also largely found it to be a positive experience, at least from the feedback that I’ve received. In one case, I was the pilot test for hosting extended virtual visits, and afterwards they told me that the experience had convinced them to do it regularly.  Going through these talks has taught me a few lessons about how to improve the experience, both for the speaker and for the audience.Always set up a time with the host to test things out in advance in the actual venue, preferably at least a few days before the talk. On the day of the talk, arrange to meet the host online at least 15 minutes before the scheduled talk time.  Even when everything is well oiled, problems can arise, and you don’t want to be debugging them in front of an audience. Give your host your cell phone number, and keep your phone handy so that they have an alternate way to contact you if necessary.  In general I think it’s good for a virtual talk to be a bit shorter than a regular talk, simply because it’s easier for people to fade off when you are not present to look them in the eye.  Erring on the side of going short rather than long is also a good general principle — As an audience member I have rarely been upset when a talk went shorter than expected, and it gives more time for questions, which are usually the most interesting part anyway. For longer talks (over an hour), give the audience a short intermission.  For example, for my talk to the Max Planck School of Cognition (a 90 min talk with 30 mins for questions), I asked the audience to stand up and stretch out about half way through, which they seemed to appreciate.I also have several suggestions for hosts of virtual visits:*Please* use a standard commercial conferencing system (like Zoom or Webex) rather than a home-grown system. Especially one that requires me to install special software! Having to install new software or log into a new system is just another potential point of failure for the talk. In general I have had the best experiences when using Zoom or Skype, but I’m sure there are other systems that are also good.   As a speaker I particularly like being able to see a chat window on my screen as I’m talking, so that people can post questions during the talk.  This works well with systems like Zoom, but often doesn’t exist at all in home-grown systems.  Please provide a camera so that the speaker can see the audience.  Talking without seeing the audience is much less pleasant and also makes it impossible to tell if people are disengaged, or if there is an unexpected problem with the A/V system.   Make clear to the audience up front how questions will work.  I prefer having them submitted by chat window, but if they are going to be spoken, then there should be microphones explicitly for the question, and these should be tested beforehand to make sure that the speaker can hear them. For extended visits, it has worked well to have a single Zoom room for the entire day, which individuals come into or out of throughout the day for their scheduled meetings.  Please remember that people sitting in front a computer have biological needs just like people who are physically present, so schedule regular bio-breaks during the day. For events that are more discussion based, it's important to have multiple microphones spread around the room so that the virtual attendees can hear what is being said.  If someone is going to be writing on a whiteboard, it's also important to have a camera on the board.Please leave other thoughts or suggestions in the comments below!  

---

## 1 comments captured from [original post](https://russpoldrack.blogspot.com/2020/01/talking-remotely-lessons-learned-so-far.html) on Blogger

**Unknown said on 2020-01-29**

Thanks so much for this - we're doing a no-aviation workshop on Friday at UCSD, and this is a really handy list from the perspective of the speaker<br />

