---
date: "2013/05/03"
title: "The dimensional approach to studying mental illness"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2013/05/the-dimensional-approach-to-studying.html)*.

The NIHM Director Tom Insel turned a lot of heads recently with his [announcement](http://www.nimh.nih.gov/about/director/2013/transforming-diagnosis.shtml) that NIMH-funded research will no longer focus on DSM-based diagnostic categories, and instead will focus on understanding the dimensions of mental function that underlie mental health disorders and often cut across multiple diagnoses.  This new focus will be centered around the [Research Domain Criteria](http://www.nimh.nih.gov/research-funding/rdoc/nimh-research-domain-criteria-rdoc.shtml) (RDoC), which comprises a set of psychological constructs that are thought to represent the most important dimensions that are relevant to mental health disorders. This is great news, as it has become clear (particularly from [recent genetic research](http://www.thelancet.com/journals/lancet/article/PIIS0140-6736(12)62129-1/abstract)) that diagnostic categories, while being statistically reliable, do not have a great deal of biological reality. Dr. Insel lays out the problem nicely:Unlike our definitions of ischemic heart disease, lymphoma, or AIDS, the DSM diagnoses are based on a consensus about clusters of clinical symptoms, not any objective laboratory measure. In the rest of medicine, this would be equivalent to creating diagnostic systems based on the nature of chest pain or the quality of fever. Indeed, symptom-based diagnosis, once common in other areas of medicine, has been largely replaced in the past half century as we have understood that symptoms alone rarely indicate the best choice of treatment.We have long been interested in this dimensional approach; in particular, it was the basis for the [Consortium for Neuropsychiatic Phenomics](http://www.phenomics.ucla.edu/) developed by my colleague Robert Bilder at UCLA several years ago, in which we are examining two specific domains of mental function (memory and executive function) across both healthy individuals and people with several different psychiatric diagnoses (schizophrenia, bipolar disorder, and ADHD).  This work is still ongoing but should start to bear fruit in the next year as the neuroimaging and genetic data analyses are completed.  It's great news that more work like this will be funded in the future.Mining for dimensionsGenetic analyses have been able to take advantage of large numbers of subjects to identify the genetic overlap between different psychiatric diagnostic groups.  Unfortunately we don't have those kinds of datasets (yet) for neuroimaging studies.  In a [paper published in PLOS Computational Biology last year](http://www.ploscompbiol.org/article/info%3Adoi%2F10.1371%2Fjournal.pcbi.1002707), we asked whether we could use the [Neurosynth](http://www.neurosynth.org/) meta-analytic database as a proxy for such data, in order to see if we can identify how different psychiatric disorders are clustered together in terms of brain function.  We first used [topic modeling](http://mallet.cs.umass.edu/topics.php) to identify groupings of terms related to psychiatric and neurological disorders in the full text of a set of about 4,400 published papers.  In some cases these were specific to single disorders, but in many cases they reflected overlapping disorders (such as alcoholism and antisocial personality disorder, or schizophrenia and bipolar disorder).  We then created "topic maps" for each of these by looking at which regions in the brain showed activity that was correlated with the presence of each topic in each paper (using the activation coordinates automatically extracted by Neurosynth).  Here are some examples of these topic maps:We then were able to ask the fundamental question that is raised by the dimensional approach: How are different diagnoses related in terms of their neural underpinnings.  It's important to keep in mind that we are not directly examining data from different diagnostic groups; instead, we are examining the neuroimaging data that are associated with the presence of those diagnostic labels across papers.  Nonetheless, the data have the potential to give us insight into how different disorders relate with regard to neural activity patterns observed in the literature.  Here is what the clustering looked like across disorders:(the abbreviations are: APH: aphasia, DLX:dyslexia, SLI: specific language impairment, DA: drug abuse, AD:Alzheimer's disease, DEP:depressive disorder, MDD:major depressive disorder, ANX:anxiety disorder, PAN: panic disorder, BPD: bipolar disorder, CD: conduct disorder, GAM: gambling, MD: mood disorder, PD: Parkinson's disease, OCD: obsessive compulsive disorder, PHO: phobia, EAT: eating disorder, SZ: schizophrenia, OBE: obesity, COC: cocaine related disorder, PSY: psychotic disorder, PAR: paranoid disorder, SZTY: schizotypal personality disorder, TIC: tic disorder, ALC: alcoholism, ALX: alexia, ADD: attention deficit disorder, AMN: amnesia, AUT: autism, ASP: Asperger syndrome.)This clustering is very interesting in that it shows that there are four major branches of mental health disorders that can be identified on the basis of brain activity coordinates from published papers: language disorders (green), mood/anxiety disorders and drug abuse (orange), psychotic and externalizing disorders (yellow), and autism and memory disorders (purple).  The fact that this worked with meta-analytic data gives us great hope that once it is applied to subject-level data, it will provide a great deal of power to identify the dimensions along which psychiatric disorders vary.How reliable are the dimensional descriptions?The move towards RDoC as a basis for mental health research also raises the question of reliability.  The strength of the DSM was that its diagnoses were reliable, in the sense that two different psychiatrists, shown the same symptoms, are highly likely to make the same diagnosis.  How will we ensure that the mappings from behavior to psychological dimensions are equally reliable?  This is a problem that we have long struggled with, and in particular was a driver for the development of our [Cognitive Atlas project](http://www.cognitiveatlas.org/).  This project aims to provide a more formal basis for the many psychological constructs that are used by researchers but rarely defined in an explicit way.  It makes a clear distinction between mental concepts (i.e. the unobservable psychological constructs that researchers want to measure) and tasks (i.e., the behavioral tests used to measure to those constructs), and most importantly, provides a way to specify the relations between those two levels.  For example, here is [the page representing the concept of "response inhibition"](http://www.cognitiveatlas.org/concept/id/trm_4a3fd79d0af66):This page provides a specific definition of the concept along with links to many different tasks that are thought to measure the concept, such as the [stop signal task](http://www.cognitiveatlas.org/task/id/tsk_4a57abb949e1a):Recently we added a new function to the Cognitive Atlas, called Collections.  A collection is a set of concepts and relations that together form a larger theoretic framework; it can also be used to identify sets of tasks that are included together in task batteries.  We have started to implement the various RDoC frameworks as Collections; for example, the [Working Memory Matrix](http://www.cognitiveatlas.org/collection/id/thc_51005496d6228):There is much more work to do, and we hope that researchers interested in RDoC will help by adding their favorite tasks and concepts to the appropriate matrices.  In the long run we are hopeful that formal frameworks like the Cognitive Atlas will come to play the same role for dimensionally-driven research that the DSM has played for diagnosis-driven research, providing a basis for reliable specification of the relations between psychological dimensions and behavioral tasks.

---

## 3 comments captured from [original post](https://russpoldrack.blogspot.com/2013/05/the-dimensional-approach-to-studying.html) on Blogger

**Sucrelege said on 2013-12-01**

Hello Dr. Poldrack,<br /><br />I originally came to your blog by way of reading about reverse inference, and was happy to discover many other interesting posts on here. I first heard about your work from when I was working as an RA in Jon Cohen's lab. Agatha was a graduate student when I worked there and had accepted a job as a post doc in your lab. She had nothing but glowing comments about you. <br /><br />Anyway, thanks for the interesting post. Implementing the RDoC approach to mental illness is an exciting watershed moment in psychopathology research. I am curious about your thoughts on graph theory approaches to mental illness that do away with the conception of mental illness as a latent variable. Below is an article that addresses this in regard to the comorbidity of depression and anxiety:<br /><br />http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0027407<br /><br />--<br />Jessica

**Russ Poldrack said on 2013-12-01**

Thanks Jessica!  I think that this is an interesting approach, though my general concern about these kinds of graph-theoretic approaches is that they don't provide much insight about mechanism - however, they can at least give you ideas about where to start looking for mechanisms.

**eat it said on 2013-12-05**

I totally agree, descriptives are not very robust without a mechanistic account.

