---
date: "2010/11/10"
title: "My Productivity Toolbox"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2010/11/my-productivity-toolbox.html)*.

 Today I’m going to say a bit about some of the tools and strategies that I use for productivity. I’ve been a fan of [GTD](http://www.davidco.com/what_is_gtd.php) since Jen introduced me to [David Allen’s book](http://www.amazon.com/Getting-Things-Done-Stress-Free-Productivity/dp/0142000280) several years ago, though I use a fairly lightweight version of it. When an email comes, I try to process it as quickly as possible, either responding to it or putting it into my to-do list (more on that below). Although I don’t always live up to it (especially when I’m traveling), I am a strong proponent of the [Inbox Zero](http://inboxzero.com/articles/) philosophy. When I see people who have thousands of emails in their inbox it makes me cringe (and it usually correlates with an inability to get things done on schedule!).Platform: My desktop platform is the 15” MacBook Pro, which I carry between home and my two offices (where I have external monitors and extra power adapters). It generally has enough juice to do anything I need, and it’s nice to have everything in one place. I previously kept a desktop machine at work and laptop for the road, but I find it more straightforward to keep everything on a single machine.Calendar: I use the mac calendar app + mobile me, which keeps everything synchronized across my computers, iPhone, and iPad. It’s well worth the yearly fee in my opinion; there are probably ways that one could achieve similar synchronization using free means, but mobile me just works so I’m happy to pay for it.To-do/GTD: I use [OmniFocus](http://www.omnigroup.com/products/omnifocus/) to manage my to-do lists and tasks. I really don’t even scratch the surface of its features, but it still works very well for me. What I particularly like is the ability to trigger new to-do items from Mail messages, which are then directly accessible within OmniFocus (including attachments). This makes life SO much easier for me that I can’t imagine living without it.Mail: I use the Mac Mail.app as my primary mail program, using IMAP to access gmail as my primary mail account; mail to all of my other addresses is forwarded to my gmail account. My main reason for using Mail.app is its nice integration with OmniFocus, as well as the ability to work offline (I like to catch up on emails in flight). Backup: I don’t back up my machine per se. However, all of my important documents are in a folder that is attached to a 100GB [Dropbox](http://www.dropbox.com/) account, which means that they are automatically synchronized across all of my machines, as well as being accessible from the web. Again, there are probably free alternatives, but I doubt any of them can offer the really solid usability of Dropbox. My only compaint is that if I add large numbers of files (e.g., digital photos), my machine gets fairly overloaded while they are being uploaded to the Dropbox server. Document sharing: Here too, Dropbox is the killer app. We have a lab dropbox that is separate from my personal dropbox, which serves as a central location for files that I can share with lab members. We recently wrote a grant using Dropbox, with authors strewn between Texas and California, and it was amazing how well it worked.PDF management: I have been using [Papers](http://mekentosj.com/papers/) for a while now, though I still am not as religious about it as some others, and I don’t actually use it for bibliographies (more on my writing workflow another time). I do find its ability to obtain papers through the UT proxy server very useful when I am off campus. Note Taking: I use [Evernote](http://www.evernote.com/) for note taking. Its greatest feature for me is the seamless integration and synchronization across my Mac, iPhone, and iPad. As with most of the other software mentioned above, I am not exactly a power user; I just use the simple features that meet my basic needs.Another tool that I have found very handy is my [Fujitsu ScanSnap ](http://www.fujitsu.com/us/services/computing/peripherals/scanners/scansnap/s1300.html)desktop document scanner, which allows me to scan in a document and attach it to an email with 1 button press and two mouse clicks. Very handy for those pesky travel reimbursement forms that always require written signatures.I'd love to hear your suggestions and comments.