---
author: "Russ Poldrack"
date: 2011/10/03
title: Signers of letter to the editor of the New York Times
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2011/10/signers-of-letter-to-editor-of-new-york.html)*.

A letter has been submitted to the editor of the NY Times regarding the outrageous Op-Ed piece by Martin Lindstrom.  (Once it is published I will add a link here.)  Because the NY Times will not allow a long list of signers on a letter, I am attaching here a list of all of the individuals who contributed to and signed the letter.  If you would like to add your name in support of the letter, please do so in the comments section.     Russell Poldrack, Ph.D., University of Texas at AustinGeoffrey K Aguirre, M.D., Ph.D., University of PennsylvaniaAdam Aron, Ph.D., University of California at San DiegoLisa Feldman Barrett, Ph.D., Northeastern UniversityMark G. Baxter, Ph.D., Mount Sinai School of MedicineSusan Bookheimer, Ph.D., University of California at Los AngelesColin Camerer, Ph.D., California Institute of TechnologyMcKell Carter, Ph.D., Duke UniversityChristopher Chabris, Ph.D., Union CollegeMolly Crockett, Ph.D., University of Zurich, SwitzerlandNathaniel Daw, Ph.D., New York UniversityPaul Downing, Ph.D., University of Bangor, Wales, UKRussell Epstein, Ph.D., University of PennsylvaniaMichael Frank, Ph.D., Brown UniversityJanet Frick, Ph.D., University of GeorgiaPaul Glimcher, Ph.D., New York UniversityTom Hartley, Ph.D., University of York, UKBenjamin Hayden, Ph.D., University of RochesterHauke R. Heekeren, M.D., Freie Universität Berlin, GermanySimon Hjerrild, M.D., University of Aarhus, DenmarkScott Huettel, Ph.D., Duke UniversityNancy Kanwisher, Ph.D., Massachusetts Institute of TechnologyBrian Knutson, Ph.D., Stanford UniversityJohn Kubie, Ph.D., SUNY Downstate Medical CenterMichael V. Lombardo, Ph.D., University of Cambridge, UKKen Norman, Ph.D., Princeton UniversityOlivier Oullier, Ph.D., Aix-Marseille University, FranceSteven Petersen, Ph.D., Washington UniversityElizabeth Phelps, Ph.D., New York UniversityRajeev Raizada, Ph.D., Cornell UniversityAntonio Rangel, Ph.D., California Institute of TechnologyPeter B. Reiner, Ph.D., University of British Columbia, CanadaGregory Samanez-Larkin, Ph.D., Vanderbilt UniversityGeoff Schoenbaum, M.D., Ph.D., University of MarylandDaphna Shohamy, Ph.D., Columbia UniversityJon Simons, Ph.D., University of Cambridge, UKPeter Sokol-Hessner, Ph.D., California Institute of TechnologyDavid Somers, Ph.D., Boston UniversityDamian Stanley, Ph.D., California Institute of TechnologyJohn Van Horn, Ph.D., University of California at Los AngelesBradley Voytek, Ph.D., University of California, San FranciscoAnthony Wagner, PhD, Stanford University.Daniel Willingham, Ph.D., University of VirginiaTal Yarkoni, Ph.D., University of Colorado BoulderJeff Zacks, Ph.D., Washington UniversityJamil Zaki, Ph.D., Harvard University

---

## 12 comments captured from [original post](https://russpoldrack.blogspot.com/2011/10/signers-of-letter-to-editor-of-new-york.html) on Blogger

**Christopher Chabris said on 2011-10-03**

Does this mean they accepted the letter, and if so, were you able to give them the revised version?

**Prefrontal said on 2011-10-03**

Completely support the letter - Craig Bennett, Ph.D., University of California at Santa Barbara

**Martin Lindstrom said on 2011-10-04**

My first foray into neuro-marketing research was for my New York Times bestseller Buyology: Truth and Lies about Why We Buy.  For that book I teamed up with Neurosense, a leading independent neuro-marketing company that specializes in consumer research using functional magnetic resonance imaging (fMRI) headed by Oxford University trained Gemma Calvert, BSc DPhil CPsychol FRSA and Neuro-Insight, a market research company that uses unique brain-imaging technology, called Steady-State Topography (SST), to measure how the brain responds to communications which is lead by Dr. Richard Silberstein, PhD.  This was the single largest neuro-marketing study ever conducted—25x larger than any such study to date and cost more than seven million dollars to run.<br /><br />In the three-year effort scientists scanned the brains of over 2,000 people from all over the world as they were exposed to various marketing and advertising strategies including clever product placements, sneaky subliminal messages, iconic brand logos, shocking health and safety warnings, and provocative product packages.  The purpose of all of this was to understand, quite successfully I may add, the key drivers behind why we make the purchasing decisions that we do.<br /><br />For the research that my recent Op-Ed column in the New York Times was based on I turned to Dr. David Hubbard, a board-certified neurologist and his company MindSign Neuro Marketing, an independently owned fMRI neuro-marketing company.  I asked Dr. Hubbard and his team a simple question, “Are we addicted to our iPhones?”  After analyzing the brains of 8 men and 8 women between the ages of 18-25 using fMRI technology, MindSign answered my question using standardized answering methods and completely reproducible results.  The conclusion was that we are not addicted to our iPhones, we are in love with them.<br /><br />The thought provoking dialogue that has been generated from the article has been overwhelmingly positive and I look forward to the continued comments from professionals in the field, readers and fans.<br /><br />Respectfully,<br /><br />Martin Lindstrom

**SJB said on 2011-10-04**

Russ, you should use this as a perfect example in your next paper on reverse inference. SJ Blakemore.

**jvs said on 2011-10-04**

Dear Mr. Lindstrom,<br /><br />When you make a claim about the emotional response people have to a product on the basis of fMRI data, you move beyond the purview of neuro-marketing and into the realm of scientific psychology and neuroscience. As a result, professionals in the field will evaluate your claim in the same manner that they would any other result in the field. And in this case, despite the overwhelmingly positive response you say you have received, the response of scientists who work in this field has been overwhelmingly negative, and for good reason. In addition to this post, see these other responses to your op-ed piece:<br /><br />http://www.talyarkoni.org/blog/2011/10/01/the-new-york-times-blows-it-big-time-on-brain-imaging/<br /><br />http://www.cultureofscience.com/2011/10/02/attention-new-york-times-readers-you-probably-do-not-love-your-iphone-literally/<br /><br />http://neurocritic.blogspot.com/<br /><br />It is simply not sufficient to say, as you do here, that MindSign used &quot;standardized answering methods and completely reproducible results&quot; and concluded that &quot;we are not addicted to our iPhones, we are in love with them.&quot; As scientists, we want to know how you and MindSign came to that conclusion. At present, there is no standardized, reproducible method for determining from fMRI data when people are or are not in love with a stimulus.<br /><br />In your op-ed piece, the only explanation you give for the conclusion that people love their iPhones is that you observed activation of insular cortex while people viewed images of an iPhone. You explain that activation of the insula is associated with feelings of love. While this is true, it is also true that activation of the insula is associated with responses to pain, feelings of disgust, and attempting to remember things over a brief delay, amongst many other things. Presumably, you would not claim that people love these things as well.<br /><br />In short, the reasoning that says that, &quot;insula activation occurs during feelings of love, therefore if the insula is activated people are experiencing love&quot; is deeply flawed. To illustrate why with an example, let us imagine that I presented people with pictures of their mother during fMRI imaging, and I observed activation in the fusiform gyrus (which I certainly would). I then present people with pictures of President Obama, and lo and behold I observe activation in the fusiform gyrus again. Should I then conclude that people think President Obama is their mother? Clearly not, and yet the same &quot;reverse inference,&quot; as it is called, was used to draw this conclusion and to conclude that people love their iPhones.<br /><br />The problem in both cases is the same: the cognitive process subserved by the activated brain region is not necessarily the one you think it is. In my example, I assumed that the cognitive process is &quot;mother recognition,&quot; when in fact research suggests that it is face recognition more generally. In your case, you assumed that the cognitive process that activated the insula was love. Unfortunately at present there is no consensus as to precisely what cognitive processes are subserved by the insula, but we can say that it is almost certainly not love, because of the wide range of situations in which the insula is activated.<br /><br />Respectfully,<br /><br />Jared Van Snellenberg

**nic said on 2011-10-04**

I support Russ' letter, Tal's letter, and Jared's response to Lindstrom's comment. Please add my name to the list! <br /><br />Nicole Giuliani, Ph.D., University of Oregon

**atlas said on 2011-10-04**

I too support the letters to the NYTimes and agree with Russ, Tal, and Jared.<br />Lauren Atlas, Ph.D.<br />New York University

**leahsom said on 2011-10-04**

I too support the rebuttal to Lindstrom's Op-Ed piece. Thank you to Russ and Tal for mobilizing the neuroscientist troops,<br />Leah Somerville PhD, Weill Cornell Medical College

**Pascal Wallisch said on 2011-10-04**

Strong agree. Didn't see this initiative until just now.<br />Pascal Wallisch, PhD, New York University

**Jochen Weber said on 2011-10-05**

Jared, I completely agree with your scientific analysis on the interpretation of the results ;) Making a claim (the 16 human subjects in the study, of which I don't know how they were selected, love iPhones) based on reverse inference (the insular cortex shows an increase in BOLD contrast upon exposure to representative stimuli) is, well, not science, but...<br /><br />I think the point of the article (let's say the two last paragraphs) was/is to raise the alarm. And while the evidence (insular cortex activation after seeing an iphone) cannot and should not be linked to the conclusion (&quot;we&quot; love iPhones), I think that it's an interesting phenomenon that might merit some research (although using more refined protocols, if possible).<br /><br />Since the behavioral aspect (e.g. people reporting a feeling of &quot;being cut off&quot; after leaving their smartphone at home) was at (or closer to) the beginning of the article (introduction?), I would rather start there... I think that there is (at least anecdotal) evidence for technologies becoming more and more intricately linked with human experience (see Betsy Sparrow's article about externalizing memories via search engines), and I would rather try to study the effect of distress upon withdrawal than that of &quot;gratification&quot; (attachment, approach, etc.) upon exposure, since that is a more salient indicator for people's report (at least as mentioned in the article...).<br /><br />Just my $0.02 though :)

**MarthaG said on 2011-10-08**

I am a non-scientist who is very fond of her technology (Android-based, for the record), and I find this conversation fascinating. As a writer and editor, I had to question Mr. Lindstrom's claim: &quot;It appears that a whole new generation is being primed to navigate the world of electronics in a ritualized, Apple-approved way.&quot; <br />My anecdotal observation--as an aunt--is that those babies who &quot;swiped&quot; the screens of Blackberries in their ritualized way probably did some other things to them--drooling, biting,hitting, and throwing--actions that don't so easily fit Mr. Lindstrom's thesis.  I welcome your thoughts.

**Shackman said on 2011-10-11**

I support the letter and related commentary by Poldrack, Van Snellenberg &amp; Yarkoni.<br /><br />Alex Shackman, Ph.D.<br />UW-Madison

