---
date: "2016/05/21"
title: "Scam journals will literally publish crap"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2016/05/scam-journals-will-literally-publish.html)*.

In the last couple of years, researchers have started to experience an onslaught of invitations to attend scam conferences and submit papers to scam journals.  Many of these seem to emanate from the OMICS group of Henderson, NV and its various subsidiaries.  A couple of months ago I decided to start trolling these scammers, just to see if I could get a reaction.  After sending many of these, I finally got a response yesterday, which speaks to the complete lack of quality of these journals.  This was the solicitation:On May 20, 2016, at 12:55 AM, Abnormal and Behavioural Psychology <[behaviouralpsychol@omicsinc.com](mailto:behaviouralpsychol@omicsinc.com)> wrote: Dear Dr. Russell A. Poldrack,Greetings from the Journal of Abnormal and Behavioural PsychologyJournal of Abnormal and Behavioural Psychology is successfully publishing quality articles with the support of eminent scientists like you.We have chosen selective scientists who have contributed excellent work, Thus I kindly request you to contribute a (Research, Review, Mini Review, Short commentary) or any type of article.The Journal is indexed in with EBSCO (A-Z), Google Scholar, SHERPA-Romeo, Open J-gate, Journal Seek, Electronic Journals Library, Academic Keys, Safety Lit and many more reputed indexing databases. We publish your manuscript within seven days of Acceptance. For your Excellent Research work we are offering huge discount in the publishing fee (70%). So, we will charge you only 300 USD. This huge offer we are giving in this month only. ...With kind regardsSincerely,Joyce V. AndriaI had previously received exactly this same solicitation about a month ago, to which I had responded like this:Dear Ms Andria, Thanks for your message.  I just spent three minutes reading and thinking about your email.  My rate for commercial consulting is $500/hour.  Can you please remit your payment of $25 to me at the address below?  I’m sure you can understand that the messages from your organization take valuable time away from scientists, and that you would agree that it’s only fair to renumerate us for this time.I look forward to receiving your payment promptly.  If you do remit within 30 days I will be forced to send this invoice out for collection.Sincerely,Russ PoldrackI got no response to that message.  So when I received the new message, I decided to step up my troll-fu:Dear Ms. Andria,Many thanks for your message soliciting a (Research, Review, Mini Review, Short commentary) or any type of article for your journal. I have a paper that I would like to submit but I am not sure what kind of article it qualifies as. The title is "Tracking the gut microbiome". The paper does not include any text; it is composed entirely of photos of my bowel movements taken every morning for one year. Please let me know if your journal has the capability to publish such a paper; I have found that many other journals are not interested.Sincerely,Russell PoldrackWithin 12 hours, I had a response: From: Abnormal and Behavioural Psychology <behaviouralpsychol@omicsinc.com>Subject: RE: Appreciated your Excellent Research workDate: May 20, 2016 at 9:47:28 PM PDTTo: "'Russell Alan Poldrack'" <russpold@stanford.edu>Dear Dr. Russell A. Poldrack,Greetings from the Journal of Abnormal and Behavioural PsychologyThank you for your reply.I hereby inform you that your article entitled: “Tracking the gut microbiome” is an image type article.We are happy to know that you want to publish your manuscript with us.We are waiting for your  earliest submission.We want to introduce your research work in this month to our Journal. We will be honored to be a part of your scientific journey.Kindly submit your article on before 26th may, 2016.Awaiting your response.,With kind regardsSincerely,Anna WatsonJournal CoordinatorJournal of Advances in Automobile EngineeringThere you have it: These journals will literally publish complete crap. I hope the rest of you will join me in trolling these parasites - post your trolls and any results in the comments.

---

## 4 comments captured from [original post](https://russpoldrack.blogspot.com/2016/05/scam-journals-will-literally-publish.html) on Blogger

**yarikoptic said on 2016-05-21**

I am pleased that you took my comment to your tweet about http://www.theverge.com/2016/5/4/11581994/fmt-fecal-matter-transplant-josiah-zayner-microbiome-ibs-c-diff so seriously :-)

**C.A. said on 2016-05-24**

I had this little exchange with the journal &quot;Translational Brain Rhythmicity&quot;:<br /><br />----------------------------------------------<br /><br />Dear Dr. Carsten Allefeld<br /><br />Greetings from Translational Brain Rhythmicity<br /><br />Hope everything is well with you!<br /><br />I would like to invite you to contribute a manuscript for the<br />upcoming issue of the journal. All submitted manuscripts will be<br />reviewed under the supervision of Dr. Marco Weiergräber.<br /><br />[...]<br /><br />Regards,<br /><br />David Randall<br />----------------------------------------------<br /><br />My reply:<br />----------------------------------------------<br />Dear David,<br /><br />thank you for your invitation. A question: Does your journal also accept contributions in the field of rotational brain rhythmicity?<br /><br />Best,<br />Carsten<br />----------------------------------------------<br /><br />An theirs:<br />----------------------------------------------<br />Yes, we do accept papers on rotational brain rhythmicity. Please, let me know by what date you will be able to submit the manuscript.<br />----------------------------------------------<br /><br />;-)

**Russ Poldrack said on 2016-05-24**

awesome!

**Unknown said on 2017-02-09**

I received one this morning from Anna Watson. Then I googled this name and the Journal name Advances in Automobile engineering. On the Journal's website, I can't find his name, making me feel suspicious. Then I saw your blog. Thanks, Russ!<br />

