---
author: "Russ Poldrack"
date: 2020/07/23
title: Vacation fun- Making traditional Texas chili con carne
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2020/07/vacation-fun-making-traditional-texas.html)*.

I’m on vacation at home this week, and one afternoon when it was especially gray (because San Francisco in July) I decided to cook up some chili con carne.  The recipe that I use is a modification of one that I can no longer find online, written by Reece Lagnuas back when he was a butcher in Austin.  I documented this cook because the recipe is such a great rendition of the traditional Texas chili that I grew up eating that I thought it should be out there for everyone to try.  And this batch turned out to be especially good! Your reward at the end of this journeyBe forewarned, this dish requires a pretty substantial time commitment - from start of prep until the dish was cooking it took me about 90 minutes.  Once it’s cooking you just need to check it occasionally to make sure it’s simmering and not cooking too hard - it should be ready to eat within 2-3 hours.  Perfect activity for a cool, gray vacation afternoon!Also - I've never written a recipe before, I apologize in advance for how verbose it is...Ingredients:Meat: I hope it goes without saying that you should only cook with humanely raised meat.  The meat for this cook came from our neighborhood butcher shop, Avedanos, which [supports local family farms](https://avedanos.com/new2019/farms/)).   ~ 2.5 pounds pork shoulder ~ 2.5 pounds brisket (preferablly from the fattier end, known variously as the point or deckle) if you have your own meat grinder then buy them whole, otherwise ask your butcher to grind them as coarsely as possible  1 large onion - diced relatively smallfresh chiles 2 red bell peppers 2 poblano peppers 2 large jalapeno peppers dried chiles - I use a varying mix, this time it was: 2 chile ancho 3 dried pasilla 2 chile guajillo seasonings: you can mix all of these together as they will be added at the same timesalt (start with 1 tbs, we like it salty so usually add more to taste later in the cook) ground black pepper (1 tsp) cayenne pepper (if you want it spicy - for this cook, I added about 1/3 tsp of Penzey’s Black & Red which is a mix of black and cayenne pepper - the end result had just a very tiny bit of spicy kick) Chili Powder (3 tbs) Ground cumin seed (2 tsp) Garlic powder (1 tbs) Onion Powder (1 tbs) Steps:Roast the fresh peppers.  The goal here is to char the skins so that they come off easily after steaming.  I used my outdoor gas grill, but you can also do this directly over the burner of a gas range.  If you don’t have gas then it sounds like you can also [use an electric range or toaster oven](https://www.foodnetwork.ca/kitchen-basics/blog/made-easy-how-to-perfectly-roast-peppers-32357/#:~:text=Using%20an%20Electric%20Stove%20(or%20Toaster%20Oven)&text=Set%20the%20oven%20to%20a,40%20minutes%20to%201%20hour.).  You want the skins to be charred black over as much of the pepper as possible, so you will need to turn them regularly; the larger peppers will probably take much longer than the small ones.  Once they are nicely charred, then put them in a loosely sealed container to steam for at least 20 minutes.Roasting the fresh chiles on the backyard gas grillRoast and rehydrate the dried chiles.  This will require a hot pan (I used the same Dutch oven that I will use to cook the chili) and about a quart of boiling water.  Heat the pan on high and toss in the chiles, turning them regularly to prevent burning.  When they start to smell roasty, place them in a heatproof bowl for soaking.  Before you soak them, use some scissors to cut small holes in the side of each chili - this will make it easier to get any air out and submerge the chiles fully. After cutting the holes, pour the boiling water over the chilis.  Roasting the dried chilesPrepare the meat.  If your meat was ground by your butcher then you can skip this step.  I like to grind the meat myself, since butchers often need time to set up their grinder for a coarse grind.  I use the meat grinder attachment for our KitchenAid mixer.  When grinding meat, it’s important for both the meat and grinder to be as cold as possible, so I put both of them in the freezer for about an hour before grinding the meat.  Chop the meat into strips or chunks that are small enough to fit in the grinder feed; I like to leave most of the fat on and remove it later during the cook, but sometimes I will trim away large fat pieces.Action shot - grinding the brisketClean and chop the chiles.  Remove the skins from the fresh chilis (they should come off easily after steaming), and also remove the stem, seeds, and membranes inside the chili.  Don’t wash them!  For the dried chiles, try to remove as much of the seeds and membrane as possible (don’t worry about the skins).  Then chop them until they are nearing the consistency of a paste; this generally takes a lot of work.Dried chiles after roastingAnother action shot - chopping chilesTime to start cooking!  Add about 2 Tbs of oil to the large pot, and cook the onions on relatively high heat until they are just starting to brown, stirring constanly.Blooming the spices - the smell is amazingAdd the spice mixture once the onions are starting to brown, and stir constantly for a minute or two. You should smell the spices bloom, especially the cumin seed.Browning the meat. After blooming the spices, add the meat and cook for several minutes until it is starting to brown. You should be able to smell the meat browning and start to see fat from the meat rendering out in the pan. Add the chili paste and mix into the meat. Then add just enough water to cover the meat; for this cook it was about 6 cups.About 3 hours in - almost done!Bring to a boil and then reduce to a simmer.  The chili will then cook for at least 2 hours and preferably 3 or more hours; for this cook, it went a bit more than 3 hours.Skim extra grease.  A couple of hours into the cook, there will likely be a substantial amount of grease on the top of the chili.  I like to remove some of this before serving, so that the chili isn’t too greasy. There are probably fancy ways to do this, but I simply use a Chinese soup spoon to skim the fat off of the top.  This time around I ended removing about 1.5 cups of fat.When you are ready to eat, taste the chili and add salt as needed to taste.Enjoy!  I don’t generally like adulterating my chili with any additions, but this time I tried it with a bit of guacamole on the side, and it was really good.This recipe makes a lot of food — we usually have enough left over from this recipe for two additional meals (for two people).  The chili keeps well in the freezer for at least a month, though it rarely lasts that long around here...  This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).