---
date: "2010/11/13"
title: "Becoming an academic road warrior"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2010/11/becoming-academic-road-warrior.html)*.

 It’s a reality that if you want to make it in academic science, you have to be ready and willing to travel a good bit. Between conferences, talks at other universities, grant review panels, and other various events in the US and abroad, I generally end up flying between 50,000 and 100,000 miles a year. Students and postdocs often ask me how I can stand to travel so much, and this post will lay out some of the strategies that I use keep myself sane while on the road. I should note up front that many of these strategies are not exactly “budget travel” ; my feeling is that I travel enough that it’s worth investing in some things that make it pleasant, but I realize that this may conflict with the realities of student or postdoc salaries.Pick an airline and stick with itI think that airline loyalty is probably the most important thing one can do to make traveling more pleasant. Most airlines have loyalty programs for people who travel at least 25,000 miles (that’s about 5 rounds trips from LA to DC, for example), and achieving this level of frequent flyer “status” comes with some very nice benefits. Foremost is access to priority check-in and priority security lines. The benefit of priority security varies between airports, but in many places (like the United terminals at LAX or O’Hare) it can save a very long wait to get through security during busy times. As your status increases, so do the benefits; in particular, once you reach “gold” status (50,000 miles on most airlines) then you become much more likely to get upgraded to first class, which is always a nice perk. Some airlines (like United) give preferred seating (with extra legroom) to frequent flyers, which makes using your laptop much more bearable. Another benefit is that you have priority for rebooking when problems occur. Finally, another benefit of loyalty is that it gives you a chance to learn the airline’s terminals and systems, which can be really useful when you are running late or things go wrong.I was a frequent flyer with United for many years, but recently switched to Continental after moving to Austin – I’ve been quite happy with both overall, and fortunately with their merger these are becoming one airline. When another institution invites you to come and give a talk, it’s perfectly legitimate to tell them what airline you want to fly on (and even what flights you want to take), and give them your frequent flyer number. This has the nice side benefit that your itinerary will show up on the airline’s online system, so you can see schedule changes and check in online.Be sure to sign up for text alerts from your airline, which will let you know about delays or upgrades. Also, when problems arise, it’s often better to call the airline directly rather than waiting in line to speak to a customer service representative when the lines are long.Join the clubIf you’ve spent any time in airports you have probably wondered what goes on inside the “Red Carpet Club” or other airline lounges. The short story is that it’s a place where you can pay to get away from the craziness of the terminal, and if you are going to fly regularly it is money well spent. It’s not cheap (generally about $400/year) but if you are flying 20 round trips in a year then that’s just $10 for each one-way trip – well worth the price IMHO. Perks include free wi-fi, snacks, and drinks (usually just beer) – unless you are in a European airport, where it generally includes a full spread of food and a full bar (though not always free wi-fi). But perhaps the most important benefit of the club is that there are customer service representatives that can help with flight problems – this is especially useful when large disruptions occur due to weather, resulting in long lines at the customer service desks out in the terminal. Keep calm and carry onNEVER check a bag unless you absolutely have to. It is certainly possible to travel for weeks with just a carry-on bag, if you pack carefully and take advantage of hotel laundry services while on the road.I have two bags that I use for most of my trips. My primary bag for trips longer than 2 days is a[ 21” expanadable carry on](http://www.briggs-riley.com/category/productDetail.aspx?id=21-inch-One-touch-Carry-On-Expandable-Upright_U421LX). I find that I can generally make it up to 4-5 days with this bag in its carry-on (un-expanded) configuration, depending on the season and what kinds of clothing I have to carry. For 1-2 day trips I use a small [carry-all](http://www.briggs-riley.com/category/productDetail.aspx?id=Wheeled-Carry-all_U214). Learning to pack can help you really maximize your carry-on space - for example, see ([Packing Tips from Professional Travelers](http://www.nytimes.com/2010/05/06/business/06PACK.html?_r=1)) - I particularly find that rolling my clothes helps to maximize packing density.Once you can afford it, buy some good luggage. I use Briggs & Riley, which is not cheap but has a lifetime warranty and has very good usability in general. Nothing sucks more than luggage failure in the middle of a trip.I also carry a [TSA-approved laptop bag](http://www.timbuk2.com/tb2/products/commute-2.0); having to remove your laptop is a pretty small thing, but every little bit counts when it comes to getting through security without stress.Stay preparedI don’t want to have to scramble the morning of my flight to find all of the toiletries that you need to take with me, so I have a separate set of toiletries that I keep ready just for travel. I use either [2 ounce Nalgene bottles](http://www.rei.com/product/402056) or [recycled pill bottles](http://www.wikihow.com/Reuse-Empty-Pill-Bottles) to hold most of my toiletries, so that I can fit everything into the TSA-approved quart bag. Some things I always bring:extra ziploc bagsearplugs (for the plane and/or the hotel)noise-cancelling headphones (I use the [Sennheiser travel headphones](http://www.sennheiserusa.com/noise-cancelling-headphones-travel-headphones_502818) which are are small and light)an energy bar (in case I miss the chance to eat between long flights)my yoga mat (to keep me flexible after too much sitting - I have a very thin and light mat that's easy to pack)for international travel: [Ambien](http://en.wikipedia.org/wiki/Zolpidem) (for sleeping on the plane and overcoming jet lag)

---

## 1 comments captured from [original post](https://russpoldrack.blogspot.com/2010/11/becoming-academic-road-warrior.html) on Blogger

**Stephan said on 2010-11-14**

Russ, This is awesome advice!

