---
author: "Russ Poldrack"
date: 2012/02/09
title: Quitting cable
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2012/02/quitting-cable.html)*.

I was inspired by [Nathan's post at Flowing Data](http://flowingdata.com/2012/02/09/why-i-want-to-quit-cable/) to say a bit about how our experiment with giving up cable TV is going. Back in September, we turned off our U-Verse subscription, sent back the DVR, and started getting our TV solely from the computer (we use a Mac Mini as our media center PC).  Here is our experience so far:We watch a lot less TV.  Our TV routine has now morphed from watching 2-3 hours per night into watching a single show every night (recent favorites are The Layover and Top Chef, with Colbert Report as our fallback).  In its place we are reading a lot more; in fact, much of the money that we are saving on cable is probably flowing to the Kindle store at Amazon.  However, we have also recently started using the [Austin Public Library's ebook lending service](http://austinlibrary.lib.overdrive.com/D31549D5-8B4D-47C2-8D5C-F1534C1E0CCF/10/845/en/Default.htm) which is a great way to save on ebooks.  I've also been playing the guitar more often.Sometimes you really want live TV.  The one problem with getting everything from the web is that it's often hard to find a good live stream; we had this problem on new year's eve.  To solve this, I recently installed a solution to allow us to view live broadcast TV from the computer, using an[Elgato EyeTV One Computer TV Tuner ](http://www.elgato.com/elgato/na/mainmenu/products/EyeTV-One/product1.en.html)with a [Mohu Leaf HDTV antenna](http://www.gomohu.com/the-leaf-indoor-hdtv-antenna/).  With this slick combination we are able to get 13 channels of over-the-air HDTV for free.  The EyeTV software is really nice; it has good DVR functionality and an integrated TV Guide.  It's very much like having cable with 13 channels, except that the DVR functions are much better than any set-top DVR we ever had.Hulu Plus  > Netflix.  We have found that Hulu Plus meets our TV viewing needs quite well.  Sure we have to watch some commercials, but we are usually able to get new shows the next day after they air, and the selection is pretty good.  I tried a free trial of Netflix online, but we have not found that it has much to offer us, except for an occasional movie.  However, we watch movies pretty rarely, and so it probably makes more sense for us to just buy them from iTunes.  For shows that are not available on the web or via Hulu (e.g., The Layover), we buy them from iTunes as well.  It's not cheap but we still come out ahead in the long run. Media center software sucks.  We tried using both Plex and Boxee on the mac mini, but gave up on both after too many things just didn't work; in particular, the Hulu integration on Plex was really frustrating, as it seems like it should work but then it never quite does.  Now we just watch Hulu content through a web browser, live/recorded TV through EyeTV, and iTunes content through iTunes.  The main drawback of this setup is that we can't get remote functionality that works seamlessly across all these different interfaces, but that's not been a problem.Overall I would rate this experiment as a success and would definitely recommend giving up cable.