---
date: "2013/04/19"
title: "On "healthy choices""
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2013/04/on-healthy-choices.html)*.

This week, I received an email describing new nutritional recommendations at one of the campus eateries:Please come by O's Campus Cafe over the next few weeks to see how they are making healthy eating easier!O's Campus Cafe has analyzed their menu and labeled their foods in order to make it easier for you to make the healthiest choices.  All foods have been given a red, yellow, or green rating based on how nutrient dense they are. Foods that have received a "Red" rating have very little positive nutrient content, are higher in unhealthy nutrients, and should be consumed minimally.  Foods that have received a "Yellow" rating have some positive nutrient content, some unhealthy nutrients, and should be consumed less often.  Foods that have received a "Green" are high in positive nutrient content, have little to no unhealthy nutrients, and can be consumed frequently.  The healthy nutrients evaluated in these developing these ratings are protein, fiber, unsaturated fat, vitamins A, C, E, B-12, thiamin, riboflavin, and folate, and minerals calcium, magnesium, iron, and potassium.  The nutrients considered unhealthy are saturated fat, cholesterol, and sodium. I would hope that guidelines regarding "healthy" choices at a major research university would be backed up with evidence, but it turns out that they were simply based on an off-the-shelf rating system (the[ Nutrient Rich Food Index](http://jn.nutrition.org/content/139/8/1549.abstract)). To see whether they are supported by actual evidence, I used PubMed to look for relevant results from randomized controlled trials; I avoided epidemiological studies given all of the difficulties in making solid conclusions from nutritional epidemiology research (e.g. [http://www.nytimes.com/2007/09/16/magazine/16epidemiology-t.html](http://www.nytimes.com/2007/09/16/magazine/16epidemiology-t.html?oref=login)). Here is what I found regarding the supposedly "unhealthy" nutrients:Reduction of saturated fat intake was associated with reduced cardiovascular events but not with any changes in all-cause or cardiovascular mortality ([Hooper et al., 2012](http://www.ncbi.nlm.nih.gov/pubmed/22592684)). A nice review of lipid metabolism by [Lands (2008)](http://www.sciencedirect.com/science/article/pii/S0163782707000549) highlights how the search for mechanisms by which saturated fats might be harmful has failed: "Fifty years later [after starting his research in the 1960's], I still cannot cite a definite mechanism or mediator by which saturated fat is shown to kill people." A review of the effects of dietary sodium reduction in randomized controlled trials showed "no strong evidence of any effect of salt reduction" on all-cause mortality ([Taylor et al., 2011](http://www.ncbi.nlm.nih.gov/pubmed/21735439)).I searched deeply on PubMed but was unable to find any systematic reviews of the effects of dietary cholesterol reduction on mortality (please let me know if you know of any); there are lots of studies looking at cholesterol reduction using statins, but that doesn't really inform the question of dietary cholesterol reduction.  However, given that serum cholesterol levels bear very little relation to dietary cholesterol intake ([Gertler et al., 1950](http://circ.ahajournals.org/content/2/5/696.full.pdf)), the labeling of dietary cholesterol as "unhealthy" seems unsupported by evidence.  The first two reviews listed above come from the Cochrane Collaboration, which is generally viewed as a highly objective source for systematic reviews in evidence-based medicine.What about the supposed "healthy" choices?I also looked for data relevant to the the health benefits of the supposedly healthy choices:A recent report from a randomized controlled trial showed that replacement of saturated fats with omega-6 linoleic acid (an unsaturated, and thus "healthy" fat) was associated with increased, rather than decreased all-cause mortality ([Ramsden et al., 2013](http://www.ncbi.nlm.nih.gov/pubmed/23386268)). This makes sense given the association of omega-6 fatty acids with inflammation (e.g. [Lands, 2012](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3475243/))  and the powerful role that inflammation plays in many diseases. Increased fiber intake in the DART (diet and reinfarction trial) of individuals who had already suffered a heart attack was associated with no effects on all-cause mortality after 10 years.([Ness et al., 2002](http://www.ncbi.nlm.nih.gov/pubmed/12032650)).  An earlier Cochrane review also showed no effects of fiber intake on incidence or recurrence of colon cancer ([Asano & McLeod, 2002](http://www.ncbi.nlm.nih.gov/pubmed/12076480)). I don't claim to be an expert in this domain, but the best evidence available seems to point towards the lack of any scientific validity of these "health" labels.  Isn't it better than nothing?One might ask whether it's still better to have some guidance that pushes people to try to eat more healthily, even if it's not supported by science.  If the recommendations were made with full disclosure of the lack of scientific evidence (ala the disclaimer on dietary supplements) then I would be ok with that. Instead, the recommendations are made in the context of a "nutritionism" that pretends that we will be healthy if we just get the right mix of healthy nutrients and avoid the bad ones, and also pretends to know which are which.  I personally would rather have no advice than unsupported pseudoadvice.At the same time, it's clear from the obesity epidemic that people need help in making better food choices, so what should we do instead?  I would propose implementing a simple rating system based the first of Michael Pollan's food rules: "Eat food".  Anything that has been freshly picked, harvested, or slaughtered would get a "healthy rating" and anything that comes from a box, can, or bag would get an "unhealthy" rating. It would be much easier than computing micronutrient values, and I challenge anyone to show that it would be any less objectively healthy than the proposed "healthy choices" which would label a fresh grass-fed steak as less healthy than a pile of french fries fried in corn oil.

---

## 2 comments captured from [original post](https://russpoldrack.blogspot.com/2013/04/on-healthy-choices.html) on Blogger

**Daniel Kessler said on 2013-05-20**

To be fair, can you point to any scientific literature that supports your recommendation to &quot;Eat food&quot;? I imagine you can, but am curious to read some literature that supports what seems common sense to me.

**Russ Poldrack said on 2013-05-20**

fair question - I'm not sure that I can point to any specific research that would support this very general claim.  would be interesting to see a randomized controlled trial that assigned people to eating highly processed vs. unprocessed foods.

