---
date: "2013/03/13"
title: "My adventures in self-quantification"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2013/03/my-adventures-in-self-quantification.html)*.

In September 2012 I began a project to characterize how my own brain function and metabolism fluctuate over the course of an entire year.  This has involved MRI scans three times a week along with blood draws once a week and daily tracking of a large set of potentially interesting variables.  This post is the first installment in my story about the experience.First, the motivation.  In the last couple of years I have become very interested in understanding the dynamics of brain function over a days-months timescale and how they relate to cognitive function and bodily metabolism.  This interest has been spurred by a number of influences, such as my growing interest in nutrition and its relation to brain function as well as my ongoing interest in better understanding psychiatric disorders.  Once I started thinking about the issue, it became very clear that there were basically no data in existence that provide any insight into how the function of an individual's brain fluctuates over such a relatively long time course. This is probably not surprising, because doing studies with volunteers that require repeated testing over a long period of time is very challenging.  At some point in 2011 it dawned upon me that I should try to bootstrap such a study by collecting data from myself.  There were several inspirations for this idea.  First was Michael Snyder's "[integrated personal omics" study](http://www.cell.com/abstract/S0092-8674(12)00166-3), published in Cell in 2011, in which he repeatedly collected blood from himself and performed a broad set of "omics" measures on his samples, which provided some interesting insights into the temporal dynamics of metabolic function.  Second was my interaction with [Laurie Frick](http://www.lauriefrick.com/), who is the artist-in-residence at the UT Imaging Research Center.  Laurie's work is based on patterns that she finds in data obtained by self-tracking, and she is deeply enmeshed in the Quantified Self movement (see [her excellent TEDx talk](http://www.youtube.com/watch?v=UDsIWKWTG6A)).  Talking to her got me increasingly interested in tracking a broader set of data about myself. The very fun book [Smoking Ears and Screaming Teeth](http://www.amazon.com/Smoking-Ears-Screaming-Teeth-Self-Experimentation/dp/B0085SKSZQ) also convinced me that self-experimentation is not (completely) crazy, and actually has long been an important tool for scientific discovery.In early 2012 I began hatching a plan to collect a broad set of data on myself.  It was essential that the all aspects of data collection were as consistent as possible in order to minimize extraneous variability in the data (such as time of day effects).  I ended up settling on a schedule of three MRI scanning sessions a week, at consistent times of day and days of the week (one afternoon and two mornings every week).  Each of the MRI scanning sessions includes a resting state fMRI scan, which will allow us to assess how functional connectivity between brain regions fluctuates over time.  In addition, once a week I perform other scans, including structural MRI (T1- and T2-weighted), diffusion tensor MRI (to assess white matter connectivity), and task fMRI (using a working memory task with faces, scenes, and chinese characters).  I also wanted to collect biological samples in order to measure the relation between bodily metabolism and brain function.  Working with some molecular biologists here at UT (along with helpful input from the Snyder lab at Stanford), we developed a protocol in which I have 20 ml of blood drawn once a week (while fasting, immediately after one of the morning MRI scans). This sample is then processed to extract RNA, white blood cells, and plasma, all of which are frozen for later analysis.  This will let us examine many different aspects of metabolism, including gene expression (via RNA sequencing), metabolomic and proteomic analyses, and other potential analyses to relate metabolism to brain function.Finally, I realized that the dataset would be most useful if I also collected as much data as possible about my daily life activities.  Working with [Zack Simpson](http://www.mine-control.com/), we developed a self-tracking app using the [Appsoma](https://appsoma.com/) framework, which allows me to easily complete surveys every morning and evening and after every MRI scan.  These data are automatically fed into a web database which is the central repository for all of the self-tracking data in the study other than MRI and biological analyses.  Some of the things that I track daily include:- blood pressure and weight (using a [FitBit Aria wireless scale](http://www.fitbit.com/aria))- foods eaten, alcohol intake, and supplements/medicines taken- exercise, time spent outdoors, and physical soreness- a free-text log of daily events- sleep quality (assessed both by subjective report and using a [ZEO sleep monitor](http://www.myzeo.com/sleep/))After every scan I also complete a [mood questionnaire](http://www.psychology.uiowa.edu/faculty/watson/PANAS-X.pdf) and also provide a structured report of what I was thinking about during the resting state fMRI scan.  I should note that other than the addition of all of these tracking activities, I have done my best to keep my life as consistent as possible and have avoided any other major lifestyle changes.With this plan in place, we began data collection on September 25, 2012.  We treated the first month as a pilot period, and made some changes to the imaging protocol to optimize data collection, beginning the production period on October 22, 2012.  In total so far we have collected 20 blood samples and 55 MRI scanning sessions.  Members of the research team have started analyzing the data, though I have made every effort not to expose myself to the results of any analyses that examine changes over time, because I don't want the results to feed back and change my behavior.  When I describe this study, many people ask if I am worried about being exposed to MRI scanning so often.  My answer has been "no", at least not with regard to the magnetic fields involved in MRI; there is no evidence of lasting effects of MRI exposure (though of course we can't ever prove that something is safe).  However, soon after the study began it became clear that there was a side effect that I had to worry about, which is the intense noise of the MRI scanner.  I have long suffered from tinnitus (which I attribute to too many loud rock shows as a youngster without ear plugs), and within the two weeks of scanning I noticed that my tinnitus was increasing.  For this reason, I went to the [UT Speech and Hearing Center](http://csd.utexas.edu/center) and had my hearing tested.  I had never had my hearing tested as an adult, but I was not terribly shocked to find out that I had quite significant high frequency hearing loss.  Because I don't want to damage my hearing any further, I have continued to get tested each month.  The results had been fairly stable until early March, when they showed about a slight worsening at 6000 Hz (consistent with a subjective increase in tinnitus around the same time).  For this reason, I am taking the month of March off of scanning, and will have my hearing re-tested at the beginning of April before resuming the scans.We will also make some changes to the MRI protocol to reduce scanner noise.  We have an [OptoAcoustics noise canceling headphone system](http://www.optoacoustics.com/medical/optoactive/features) in place at our imaging center that works quite well to reduce the noise of the functional MRI scans, so those can continue without much danger.  However, we will likely discontinue some of the other scans (such as gradient field maps, which are useful but not necessary) and greatly reduce the frequency of others that we don't expect to change much over time (including the anatomical and diffusion scans), because those scans are not compatible with the noise cancellation system.  I am hopeful that with these changes I can continue scanning without danger of further hearing damage, while still collecting a very useful dataset.  Assuming that I am able to continue scanning, I plan to collect 50 weeks worth of usable data, which should provide sufficient power for an initial set of analyses.  This will likely take though the end of 2013 due to travel and other events that will interfere with data collection during some weeks.  Once we have completed our initial set of analyses, nearly all of the data will be made available to other researchers, which I hope will help spur new analyses.  I'll keep you all posted as the study moves along.

---

## 8 comments captured from [original post](https://russpoldrack.blogspot.com/2013/03/my-adventures-in-self-quantification.html) on Blogger

**practiCal fMRI said on 2013-03-13**

Nice. I was thinking of doing a 24-hr study on myself last summer, with scans every 90 mins or so. But diurnal effects are well researched by others, it was really just an excuse to offer myself as a lab rat. I, too, have no fear of the exposure effects of the MRI. Indeed, I reckon a clever statistician could show that I am safer for the time spent in the MRI than a similar amount of time spent driving my car.<br /><br />Good luck with the tinnitus. Nasty. I assume you're using the 12ch head coil and using the Siemens pneumatic headphones? Try dispensing with the latter entirely, and use instead those green curved foam pieces either side of your head (along with the standard ear plugs). My experience is that total hearing protection (and comfort) is improved by omitting headphones entirely. Be interesting to try that approach vs your ANR headphones. As you're an experienced subject you probably don't need to hear the operator clearly over the bore speaker.

**Russ Poldrack said on 2013-03-13**

I'm actually using the 32ch Siemens coil and the optoacoustics headphones over foam earplugs.  interesting idea about trying the foam, will give that a shot.  At this point I know exactly what is going to happen during the scan, and the only reason they talk to me is so that I can swallow before the scan starts :-).

**practiCal fMRI said on 2013-03-13**

Even better! In the 32ch coil I've found the green foam to be more comfortable and better sound protection than anything I can contrive in the 12ch coil.

**Unknown said on 2013-03-13**

russ, have you you considered switching to a spiral pulse sequence? the high-frequency pinging of EPI could be especially damaging. spirals make a nice low-frequency hum.<br />

**Russ Poldrack said on 2013-03-13**

Thanks Eli - interesting suggestion.  I had not considered this, mostly because I don't think there is currently a multiband spiral sequence for Siemens machines, and I would not want to give up the substantial performance benefits we get from multiband imaging (e.g., right now are getting 64 slices at 2.4 mm isotropic resolution in 1.16 seconds).

**Guillaume said on 2013-03-21**

Fascinating project, I'm very curious about the outcomes!<br />I was also wondering about the ethical implications: did you have to obtain approval from an ethical committee before starting the project, and are you potentially concerned with sharing such personal data?

**Russ Poldrack said on 2013-03-21**

Thanks Guillaume - My local IRB has reviewed the project and made the determination that it does not meet the definition of &quot;human subjects research&quot; which is &quot;a systematic investigation designed to develop or contribute to generalizable knowledge&quot;, because a study of a single individual is not generalizable.  In addition, it does not involve any recruitment of human volunteers, just the PI (me).  <br /><br />I am somewhat concerned about sharing identifiable personal data.  I will most likely make the data available under a data sharing agreement that prevents the further sharing of the data or the disclosure of any health-related findings from the data without my permission.

**Russ Poldrack said on 2013-04-07**

thanks for the tip!

