---
author: "Russ Poldrack"
date: 2023/07/28
title: An update on moving from MacOS to Linux on the desktop
---

It's been about eight months since I [switched to Linux on the desktop](https://poldrack.github.io/blog/posts/moving-from-mac-to-linux-finally/) - here's an update. The TL;DR is that I am overall very happy that I made the switch. 

My favorite thing about moving is that I feel much more in control of my system than I did on the Mac, due to all of the recent security "improvements" on MacOS. No hidden filesystems, no app restarts due to system permissions, no fighting with the system to install non-certified software packages.  Most software updates can be done without a reboot, and all of them can be done from the command line.  When a reboot is required, it's quick; no more sitting with the machine unavailable for long periods of time waiting for a system update.  I would liken the difference to driving a car with a manual transmission versus an automatic; it takes a bit more practice to drive with a stick, but the experience is much more direct and (for many people) much more fun than driving with an automatic.

There are very few things that I could do on the Mac that I can't do on Linux. Fortunately, in those cases there are generally cloud services that I can use. The one I use most commonly is Adobe Acrobat, which I sometimes require to work with PDF portfolios and signing of PDFs. The cloud version of Acrobat (paid subscription) has worked well for this. I've also occasionally needed to use the Office365 version of Word.

I still keep my Mac around, for one main reason: music. I like to play guitar directly from the computer (so I can mix it with music to play along) and control my HX Stomp via USB using the HX Edit app. There is simply no comparison in the level of music support in Linux compared to MacOS.

One thing I am still not loving is my presentation workflow. I started out using Quarto to build my talks, and I loved it for a while, but at some point I got tired of spending way too much time on manual positioning of graphic elements. So, in the last few months I have largely switched to using Google Slides. I don't love the interface (in particular, I find the template workflow annoying) but overall it works fine. The clincher for me has been the ease with which I can convert my old keynote slides using @cloudconvert, which somehow seens to do a better job of converting than Keynote's own pptx exporter!  

Hardware-wise I am fairly happy with the Thinkpad X1.  I've also gotten good feedback from others about the laptops from [Framework](https://frame.work/), which are modular and highly customizable, as well as those from [System76](https://system76.com/).  It turns out that having a Linux laptop can often be a conversation-starter!

Overall I would highly recommend trying out the switch if you are curious, but I would also add the following *nota bene*: My experience may not be universal, given that I have significant experience with Linux system administration.  I don't feel like it has come up very often, but on occasion it's been really useful to have enough sysadmin skills to feel comfortable messing with system files.  The most notable example is that at one point my `/boot` partition became full because of a number of older kernels that were hanging around and were not being removed by the `autoremove` function, which prevented updating of the kernel.  I had to delete some of these files by hand to make room for the new kernel, which would be a pretty bad idea unless you really know what you are doing.  Another place it has come up is in security configuration, where I wanted to configure my machine with more stringent settings than default, such as changing the SSH port from the default setting.  Less experienced users would probably be stuck blindly copying and pasting commands from Stack Overflow, which usually works but can on occasion be a recipe for disaster.  

One could almost certainly use Linux on the desktop without knowing any sysadmin skills and probably be fine 99% of the time, but I would be nervous about recommending it for one's primary system, especially on the road.  On the other hand, how better to get those skills than trial by fire! I learned them first by playing with my own systems as side projects, and then when I ran a cluster for our lab at UCLA (which I would definitely not recommend - there is a reason that sysadmin is a separate job description from faculty member!).  If you are nervous about it, you can always [try out Linux in a virtual machine](https://itsfoss.com/why-linux-virtual-machine/) before going all in.