---
date: "2015/08/26"
title: "New course on decision making: Seeking feedback"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2015/08/new-course-on-decision-making-seeking.html)*.

I am currently developing a new course on the psychology of decision making that I will teach at Stanford in the Spring Quarter of 2016. I've looked at the various textbooks on this topic and I'm not particularly happy with any of them, so I am rolling my own syllabus and will use readings from the primary literature.  I have developed a draft syllabus and would love to get feedback: Are there important topics that I am missing?  Different readings that I should consider?  Topics I should consider dropping?  Please leave comments with your suggestions, or email me at poldrack@gmail.com!Part 1: What is a decision? 1. Varieties of decision making (overview of course)Part 2: Normative decision theory: How an optimal system should make decisions2. axiomatic approach from economics- TBD reading on expected utility theory3. Bayesian decision theoryKörding, K. P. (2007). Decision Theory: What “Should” the Nervous System Do? Science, 318(5850), 606–610. [http://doi.org/10.1126/science.1142998](http://doi.org/10.1126/science.1142998)4. Information accumulationSmith & Ratcliff, 2004, Psychology and neurobiology of simple decisions.  TINS.Part 3: Psychology: How humans make decisions5. Anomalies: the ascendence of psychology and behavioral economicsKahneman, D. (2003). A perspective on judgment and choice. American Psychologist,58, 697-7206. Judgment: Anchoring and adjustmentChapman, G.B. & Johnson, E.J. (2002). Incorporating the irrelevant: Anchors injudgment of belief and value7. Heuristics: availability, representativenessTversky, A., & Kahneman, D. (1974). Judgment under uncertainty: Heuristics and biases.Science, 185, 1124-1131. 8. Risk and uncertainty: Risk perception, risk attitudesSlovic, P. (1987). Perception of risk. Science, 236, 280-2859. Prospect theory Kahneman, D. & Tversky A. (1984). Choices, values, and frames. AmericanPsychologist, 39, 341–350.10. Framing, endowment effects, and applications of prospect theoryKahneman, D., Knetsch, J.L., & Thaler, R.H. (1991). The endowment effect, lossaversion, and status quo bias. Journal of Economic Perspectives, 5, 193-206.11. Varieties of utilityKahneman, Wakker, & Sarin (1997). Back to Bentham: Explorations of experienced utility.  Quarterly Journal of Economics.12. Intertemporal choice and self-controlMischel, W., Shoda, Y., & Rodriguez, M.L. (1989). Delay of gratification in children. Science, 244, pp. 933-938.13. Emotion and decision makingRottenstreich, Y. & Hsee, C.K. (2001). Money, kisses and electric shocks: On theaffective psychology of risk. Psychological Science, 12, 185-190.14. Social decision making and game theoryTBDPart 4: Neuroscience of decision making15. Neuroscience of simple decisionsSugrue, Corrado, & Newsome (2005). Choosing the greater of two goods: neural currencies for valuation and decision making. Nature Reviews Neuroscience.16. Neuroscience of Value-based decision makingRangel et al., 2008, A framework for studying the neurobiology of value-based decision making17. Reinforcement learning and dopamine, wanting/likingSchultz, Montague, and Dayan (1997) A neural substrate of prediction and reward18. Decision making in simple organismsReading TBD (c. elegans, snails, slime mold, etc)possibilities:[http://www.ncbi.nlm.nih.gov/pubmed/10737805](http://www.ncbi.nlm.nih.gov/pubmed/10737805)[http://www.sciencemag.org/content/311/5767/1613.full](http://www.sciencemag.org/content/311/5767/1613.full)[http://rspb.royalsocietypublishing.org/content/278/1703/307](http://rspb.royalsocietypublishing.org/content/278/1703/307)Part 5: Ethical issues19. Free willRoskies (2006) Neuroscientific challenges to free will and responsibility.OR:Shadlen & Roskies (2012). The neurobiology of decision-making and responsibility: reconciling mechanism and mindedness. 

---

## 3 comments captured from [original post](https://russpoldrack.blogspot.com/2015/08/new-course-on-decision-making-seeking.html) on Blogger

**Unknown said on 2015-09-03**

You might consider something on evidence accumulation - Ratcliffe 1978, Gold &amp; Shadlen 2007

**Christina said on 2015-09-30**

1) Perceptual decision making and how it relates to value-based decision making (http://www.nature.com/nature/journal/v431/n7010/full/nature02966.html)<br />2) We had a pretty good discussion on neuromarketing in our decision-making class (http://www.ncbi.nlm.nih.gov/pubmed/20197790). Might fit into &quot;ethics&quot;. Cheers from Berlin! Christina

**Doctor Spurt said on 2015-12-14**

You might find some interesting stuff in some old (late 1970s) Quantitative Ethology literature, in particular McFarland &amp; Sibley's &quot;The Behavioural Final Common Path&quot;. (http://www.ncbi.nlm.nih.gov/pubmed/239416) And even if you don't, ethology seems to be missing from your working outline.

