---
date: "2011/10/04"
title: "NYT Letter to the Editor: The uncut version"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2011/10/nyt-letter-to-editor-uncut-version.html)*.

The NY Times has now printed [our letter to the editor](http://www.nytimes.com/2011/10/05/opinion/the-iphone-and-the-brain.html) regarding the Lindstrom article.  However, the published version is an edited and shortened version of our original letter, which I am posting here for the record.Dear Editor,The Op-Ed “You Love Your iPhone, Literally” by Martin Lindstrom purports to show, using brain imaging, that our attachment to digital devices, reflects not addiction but instead the same kind of emotion that we feel for human loved ones. However, the evidence the author presents does not show this.  The region that he points to as being “associated with feelings of love and compassion” (the insular cortex) is a brain region that is active in [as many as one third of all brain imaging studies](http://www.nature.com/nmeth/journal/v8/n8/full/nmeth.1635.html).  Further, in studies of decision making the insula is more often associated with negative than positive emotions.  The kind of reasoning that Lindstrom uses is well known to be flawed, because there is rarely a one-to-one mapping between any brain region and a single mental state; insula activity could reflect one or more of several psychological processes. This same point [was made by some of us](http://www.nytimes.com/2007/11/14/opinion/lweb14brain.html) regarding a [similar Op-Ed piece in 2007](http://www.nytimes.com/2007/11/11/opinion/11freedman.html)). We are disappointed that the Times has published extravagant claims based on scientific data that have not been subjected to the standard scientific review process, especially considering how often its pages exhort policy makers to pay more attention to peer-reviewed scientific evidence and disregard specious claims.Sincerely,Russell Poldrack, Ph.D., University of Texas at AustinGeoffrey K Aguirre, M.D., Ph.D., University of PennsylvaniaAdam Aron, Ph.D., University of California at San DiegoLisa Feldman Barrett, Ph.D., Northeastern UniversityMark G. Baxter, Ph.D., Mount Sinai School of MedicineSusan Bookheimer, Ph.D., University of California at Los AngelesColin Camerer, Ph.D., California Institute of TechnologyMcKell Carter, Ph.D., Duke UniversityChristopher Chabris, Ph.D., Union CollegeMolly Crockett, Ph.D., University of Zurich, SwitzerlandNathaniel Daw, Ph.D., New York UniversityPaul Downing, Ph.D., University of Bangor, Wales, UKRussell Epstein, Ph.D., University of PennsylvaniaMichael Frank, Ph.D., Brown UniversityJanet Frick, Ph.D., University of GeorgiaPaul Glimcher, Ph.D., New York UniversityTom Hartley, Ph.D., University of York, UKBenjamin Hayden, Ph.D., University of RochesterHauke R. Heekeren, M.D., Freie Universität Berlin, GermanySimon Hjerrild, M.D., University of Aarhus, DenmarkScott Huettel, Ph.D., Duke UniversityNancy Kanwisher, Ph.D., Massachusetts Institute of TechnologyBrian Knutson, Ph.D., Stanford UniversityJohn Kubie, Ph.D., SUNY Downstate Medical CenterMichael V. Lombardo, Ph.D., University of Cambridge, UKKen Norman, Ph.D., Princeton UniversityOlivier Oullier, Ph.D., Aix-Marseille University, FranceSteven Petersen, Ph.D., Washington UniversityElizabeth Phelps, Ph.D., New York UniversityRajeev Raizada, Ph.D., Cornell UniversityAntonio Rangel, Ph.D., California Institute of TechnologyPeter B. Reiner, Ph.D., University of British Columbia, CanadaGregory Samanez-Larkin, Ph.D., Vanderbilt UniversityGeoff Schoenbaum, M.D., Ph.D., University of MarylandDaphna Shohamy, Ph.D., Columbia UniversityJon Simons, Ph.D., University of Cambridge, UKPeter Sokol-Hessner, Ph.D., California Institute of TechnologyDavid Somers, Ph.D., Boston UniversityDamian Stanley, Ph.D., California Institute of TechnologyJohn Van Horn, Ph.D., University of California at Los AngelesBradley Voytek, Ph.D., University of California, San FranciscoAnthony Wagner, PhD, Stanford University.Daniel Willingham, Ph.D., University of VirginiaTal Yarkoni, Ph.D., University of Colorado BoulderJeff Zacks, Ph.D., Washington UniversityJamil Zaki, Ph.D., Harvard University