---
date: "2011/06/30"
title: "Recent Reads"
author: "Russ Poldrack"
---

*This was originally posted on blogger [here](https://russpoldrack.blogspot.com/2011/06/recent-reads.html)*.

Here are my thoughts about some books I have read recently.Hits:T[he Emperor of All Maladies: A Biography of Cancer](http://www.amazon.com/Emperor-All-Maladies-Biography-Cancer/dp/1439107955/ref=sr_1_1?s=books&ie=UTF8&qid=1309457348&sr=1-1):  An absolutely fascinating book.  It traces the history of cancer and its treatment, highlighting all of the ways in which medical science has gotten things wrong in the past and how cancer treatment has only recently evolved beyond blindly poisoning the body.  Not a lot of scientific content, but more than enough to keep me interested.  [Food and Western Disease](http://www.amazon.com/Food-Western-Disease-evolutionary-perspective/dp/1405197714/ref=sr_1_1?ie=UTF8&s=books&qid=1309456491&sr=8-1): Staffan Lindenberg is a physician from Sweden who is best known for the [Kitava Study](http://www.staffanlindeberg.com/TheKitavaStudy.html).  This book is a systematic review of the evidence regarding dietary causes of western disease such as cancer, diabetes, and heart disease.  He's clearly an advocate for the paleo diet, but he seems pretty fair in saying when the evidence does or does not fit with that approach. Definitely worth reading.[The Queen of Fats](http://www.amazon.com/Queen-Fats-Omega-3s-Removed-California/dp/0520253809/ref=sr_1_1?ie=UTF8&s=books&qid=1309457144&sr=1-1): This is a relatively obscure book from a university press, but turned out to be a great read.  The writer is not a scientist but does a decent job of covering the science, while still making the story engaging and fun.  It has definitely changed how I think about food.[The Immortal Life of Henrietta Lacks](http://www.amazon.com/Immortal-Life-Henrietta-Lacks/dp/1400052181/ref=sr_1_1?s=books&ie=UTF8&qid=1309456728&sr=1-1): I found this book fairly engaging, though it was a bit too tilted towards the drama of the writer's journey versus the story itself.  What I found most interesting were the stories about how absolutely messed up the Lacks family was (e.g., the children were all partly deaf due to a combination of inbreeding and neurosyphilis).  However, I would have liked more scientific content.  I would definitely recommend this book as background for human researchers as it really highlights the reasons why we have such strict control over human research today. [Superbug](http://www.amazon.com/Superbug-Fatal-Menace-Maryn-McKenna/dp/1416557288/ref=sr_1_1?s=books&ie=UTF8&qid=1309457258&sr=1-1): The Fatal Menace of MRSA:  I know that I am crazy for reading these kinds of books as they just make one paranoid about infections, but nonetheless I found it really engaging and interesting.  Not for the squeamish or hypochondriacal, however. [Do The Work](http://www.amazon.com/Do-the-Work-ebook/dp/B004PGO25O):  This is a motivational book targeted largely at writers, but would be really useful for many researchers to read.  It discusses how we often get in our own way, and how to get around it.  It's definitely a different kind of book from the rest of these, but for anyone who is having trouble getting things done I would highly recommend it.Misses:[The Information - A History, A Theory, A Flood](http://www.amazon.com/Information-History-Theory-Flood/dp/0375423729/ref=sr_1_1?s=books&ie=UTF8&qid=1309457729&sr=1-1):  This book is about the history of information theory, and thus will appeal to my geekier friends.  Gleick is a great writer, and it starts really strong and does a good job of explaining lots of concepts, but I thought that the end fell really flat.  I would recommend only if you are really seriously interested in the topic.[Bossypants](http://www.amazon.com/Bossypants-Tina-Fey/dp/0316056863/ref=sr_1_1?s=books&ie=UTF8&qid=1309457651&sr=1-1):  I am generally a big Tina Fey fan and I really wanted to like this, but it just didn't work for me.  I made it about 1/3 of the way in before I gave up. [Everything is obvious: *once you know the answer](http://www.amazon.com/Everything-Obvious-Once-Know-Answer/dp/0385531680/ref=sr_1_1?s=books&ie=UTF8&qid=1309457944&sr=1-1):  I absolutely loved Duncan Watts' earlier book, [Six Degrees](http://www.amazon.com/Six-Degrees-Science-Connected-Market/dp/0393325423/ref=sr_1_3?s=books&ie=UTF8&qid=1309458007&sr=1-3),   so I was really excited to read this.  In addition, the topic is really fascinating and ripe for the picking.  However, I was really disappointed and barely made it through a couple of chapters.  The problem is that it's written for executives, and thus is peppered with dumbed-down examples without enough deep explanation.  I think it's a great example of how not to write a popular science book.

---

## 1 comments captured from [original post](https://russpoldrack.blogspot.com/2011/06/recent-reads.html) on Blogger

**Bob said on 2011-06-30**

I like Tina Fey, but generally as soon was someone starts blabbering about their kids or parenting I am OUT!

